name: renovate

on:
  schedule:
    - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: spotdemo4/better-checkout@caa4005d39c5ed24e309c1272e774d0319bbed7d # v0.14.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@973d3e5a68e735a444e8c03432b66eedb343c302 # v46.2.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.checkout.outputs.token }}
